### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by JoshuaFox** [saidababu/ai-ml-bb#3]
At https://github.com/saidababu/ai-ml-bb/blob/main/week3/day3/capstone/Banking%20Fraud.md

Image not found: https://github.com/saidababu/ai-ml-bb/raw/main/week3/day3/capstone/Images/rcf_datahead.png

**Comment by aboavent** [comment]
Thanks for pointing this out. Just uploaded the images folder and it is working now
