### ISSUE TITLE
Link needed

### ISSUE THREAD

**Issue by JoshuaFox** [saidababu/ai-ml-bb#4]
https://github.com/saidababu/ai-ml-bb/blob/main/week3/day3/capstone/Banking%20Fraud.md

mentions `Starter-Code/Multithreaded_Ensemble_Modeling.ipynb`

But I cannot find that on  github.com/saidababu/ai-ml-bb nor on github.com/awslabs/amazon-sagemaker-examples

**Comment by aboavent** [comment]
File added to the repo - Starter-Code/Multiprocess%20Ensembler.ipynb
